on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: build

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      VAULTR_TEST_SERVER_INSTALL: true
      VAULTR_TEST_SERVER_PORT: 18200

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

    name: Install orderly
    run: |
      install.packages("drat")
      drat:::add("vimc")
      install.packages("orderly")
    shell: Rscript {0}

    name: Build
    run: |
      orderly:::run_orderly_demo(".")
    shell: Rscript {0}
